### PR TITLE
Add option to change sign highlight group.

### PR DESCRIPTION
**Pull request by WloHu**

### CODE REVIEW

**Comment by WloHu** [comment]
I like it better. I squashed the changes.

**Comment by AndrewRadev** [comment]
Thanks :). If you can think of a more appropriate default, I might consider changing it, too. Currently wondering if `DiffChange` is not more appropriate, for instance.

**Comment by WloHu** [comment]
`Diff...` highlight groups make sense in a way that "This section is going to be diffed" but I don't know which would be the best pick. However my first thought was to use `LineNr`, `FoldColumn` or `SignColumn` because they are related to the same editor area (the gutter).

**Comment by AndrewRadev** [comment]
Yes, that would make sense. My `SignColumn` doesn't seem to have any highlighting, though, and `FoldColumn` feels a bit confusing to me (is that an actual fold, or the linediff markers?). Well, I'll leave it as "Search" by default, and it does seem like something that really depends a lot on the user's preference.

**Pull request merged**
